labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please search existing [Discussions](https://github.com/jsattler/Pulse/discussions?discussions_q=category%3AIdeas) and [Issues](https://github.com/jsattler/Pulse/issues?q=sort%3Areactions-desc) before opening a new feature request to avoid duplicates.

  - type: markdown
    attributes:
      value: "# Feature Request"

  - type: textarea
    attributes:
      label: Problem Statement
      description: |
        Describe the problem or limitation you are experiencing. What workflow is difficult or impossible today?
      placeholder: |
        I want to monitor a custom HTTP endpoint, but currently I can't configure basic auth.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Describe the feature or change you would like to see. Be as specific as possible about the expected behavior.
      placeholder: |
        Add basic auth support to the HTTP monitoring provider.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds? If so, please describe them.
      placeholder: |
        I currently use a script to check the status and report it elsewhere.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or references that help illustrate your request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Acknowledgements"

  - type: checkboxes
    attributes:
      label: "I confirm that:"
      options:
        - label: I have searched existing Discussions and Issues and this is not a duplicate.
          required: true
